[#271] design 다크모드 대응 완료!!
DeveloperAcademy-POSTECH/MacC-TEAM-8bit pull request #275
Opened 2022-11-26 23:43 UTC by RuyHa

### 작업 내용 설명
1. 다크 모드 작업을 했습니다.
2. 멋진 디자인과 같이 코드 작업을 해주신 디자이너 린다에게 무한한 감사를...

### 관련 이슈
- #271 

### 작업의 결과물
- 린다와 같이 하나하나 확인 했으나 한번씩 확인 해 주시면 좋을 것 같습니다.
- 제어센터의 다크모드를 적용시키면 확인 가능합니다.

### 작업의 비고사항 및 한계점
- 린다에게 한계란 없습니다.

### To Reviewers
- 리뷰어에게 중점적으로 살펴봐줬으면 하는 내용

Close #271

2022-11-26 23:52 UTC, RuyHa commented on OrrRock/OrrRock.xcodeproj/project.pbxproj
> -				INFOPLIST_KEY_UIUserInterfaceStyle = Light;
이제 특정 모드만 사용하지 않기에 삭제한 코드입니다.

2022-11-26 23:52 UTC, RuyHa commented on OrrRock/OrrRock/Extensions/Color+.swift
> +    static let orrGray050 = UIColor(named: "oRGray050")
orrGray050 이 추가 되었습니다.

2022-11-26 23:52 UTC, RuyHa commented on OrrRock/OrrRock/Extensions/Color+.swift
> +    static let orrGray050Custom = UIColor(named: "oRGray050Custom")
다크모드 대응을 위한 색상입니다. 새로운 뷰를 그릴때 꼭 디자인 가이드를 확인 부탁드립니다.
(뷰 디자인 코드 생성시 다크모드도 확인!!)

2022-11-26 23:52 UTC, RuyHa commented on OrrRock/OrrRock/Home/HomeViewController.swift
> +    }()
다크모드 라이트모드 변환시 특정 색상이 바뀌지않는 이슈 해결을 위해 따로 분리 했습니다.

2022-11-26 23:52 UTC, RuyHa commented on OrrRock/OrrRock/Home/HomeViewController.swift
> +    }
분명 다크모드 라이트 모드 색상이 설정되어 있는데 앱 실행중 변환시 적용이 안된다면
바뀌어야 되는 부분의 색상 입력을 해당 코드 안에 작성해 주시면 됩니다.
```swift
if (traitCollection.hasDifferentColorAppearance(comparedTo: previousTraitCollection)) {
              //여기에 작성
           }
```
해당 코드는 다크모드 라이트모드 전환시 호출 되는 코드입니다.

2022-11-26 23:52 UTC, RuyHa commented on OrrRock/OrrRock/MyActivity/SwiftUIChartView/ChallengeChartView.swift
> +                }
여백 이슈로 수정 했습니다. ( 디자이너 요청)

2022-11-26 23:52 UTC, RuyHa commented on OrrRock/OrrRock/MyActivity/SwiftUIChartView/ChallengeChartView.swift
> -        )
테두리 삭제 요청으로 인한 코드 제거

2022-11-26 23:52 UTC, RuyHa commented on OrrRock/OrrRock/Upload/GymSettingViewController.swift
> +    }
위에 작성한 코드와 같습니다. 중요해서 두번 커멘트 남깁니다.
다크모드, 라이트모드 전환시 호출되는 함수입니다.

2022-11-26 23:52 UTC, RuyHa commented on OrrRock/OrrRock/Upload/UIComponent/View/SwipeableCardVideoView.swift
> +        videoBackgroundView.layer.borderColor = myColor?.withAlphaComponent(1.0).cgColor
카드 스와이프 테투리 색상을 설정해주는 코드입니다.
다크모드 라이트모드 대응을 위해 색상값을 RBG가 아닌 지정색을 추가해야 하기에 변경 했습니다.

2022-11-27 08:33 UTC, commitcomplete approved these changes
번거로운 작업이었을텐데 수고하셨습니다! 한층더 자연스럽고 유동적인 UI가 되어가네요!

2022-11-27 08:33 UTC, commitcomplete commented on OrrRock/OrrRock/Home/HomeViewController.swift
> +           }
저희 앱은 iOS 16.0 버전부터 지원하는 것으로 알고 있는데 13.0 이상으로 분기처리를 넣은 이유가 있을까요?

2022-11-27 08:33 UTC, commitcomplete commented on OrrRock/OrrRock/Home/HomeViewController.swift
> +    private func showOnBoard(){
```suggestion
    private func showOnBoard() {
```
와 같이 수정부탁드립니다!

2022-11-27 09:28 UTC, sm-amoled requested changes
다크모드 변경 패치와 함께 발생한 것으로 보이는 문제 상황들에 대해서 수정이 필요합니다!

VideoCollectionView 내에서 편집모드 진입 → 취소 시 네비게이션바 아이템이 제대로 초기화되지 않고 있습니다.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/39216546/204127670-28b55f40-407c-4cc0-9974-d2d631d39b6a.png">

레벨 수정 시 피커의 백그라운드 색상이 어색하게 남아있습니다.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/39216546/204127739-ca4b810b-7383-4e2f-9d11-ebf708c6571a.png">

다크모드에서 공유된 영상은 제대로 글자색상이 지정되지 않습니다.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/39216546/204128173-bdb871f0-e6de-4f16-b8d3-2c86cf46efb0.png">

온보딩의 색상이 스케치 디자인파일과 다릅니다.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/39216546/204129843-576f2feb-92d5-457f-a75a-0e3401208776.png">

2022-11-27 11:13 UTC, sm-amoled commented
남겨주신 코드 수정사항 대부분 다 확인하고 인지했습니다! 2가지 질문사항이 있어요.
1. 현재 라이트모드 사용자의 경우에는 라이트모드 → 다크모드 → 라이트모드 / 다크모드 사용자의 경우에는 계속 다크모드가 유지되는 형태일텐데, 임의로 컬러모드를 전환시키기 위해서는 `viewWillAppear()` 호출 시 어떤 함수를 실행 혹은 어떤 설정값을 변경해주면 해주면 되나요?
2. 스케치 상에 새로 추가된 커스텀 컬러가 없던데 어떤 기준으로 적용되나요?

2022-11-27 11:16 UTC, sm-amoled commented on OrrRock/OrrRock.xcodeproj/project.pbxproj
> -				INFOPLIST_KEY_UIUserInterfaceStyle = Light;
남겨주신 코드 수정사항 대부분 다 확인하고 인지했습니다! 2가지 질문사항이 있어요.

1. 현재 라이트모드 사용자의 경우에는 라이트모드 → 다크모드 → 라이트모드 / 다크모드 사용자의 경우에는 계속 다크모드가 유지되는 형태일텐데, 임의로 컬러모드를 전환시키기 위해서는 `viewWillAppear()` 호출 시 어떤 함수를 실행 혹은 어떤 설정값을 변경해주면 해주면 되나요?
2. 스케치 상에 새로 추가된 커스텀 컬러가 없던데 어떤 기준으로 적용되나요?

2022-11-27 11:31 UTC, drin131 commented on OrrRock/OrrRock.xcodeproj/project.pbxproj
> -				INFOPLIST_KEY_UIUserInterfaceStyle = Light;
2. 스케치 상에 새로 추가된 커스텀 컬러가 없던데 어떤 기준으로 적용되나요?
orrGray950이랑 orrGray050 컬러가 추가되었습니다! 주로 모든 탭(기록/내활동/추후에 추가될 루트파인딩) 메인의 BG 컬러로 쓰입니다~

2022-11-27 13:45 UTC, RuyHa commented
> 다크모드 변경 패치와 함께 발생한 것으로 보이는 문제 상황들에 대해서 수정이 필요합니다!
> 
> VideoCollectionView 내에서 편집모드 진입 → 취소 시 네비게이션바 아이템이 제대로 초기화되지 않고 있습니다. <img alt="image" width="300" src="https://user-images.githubusercontent.com/39216546/204127670-28b55f40-407c-4cc0-9974-d2d631d39b6a.png">
> 
> 레벨 수정 시 피커의 백그라운드 색상이 어색하게 남아있습니다. <img alt="image" width="300" src="https://user-images.githubusercontent.com/39216546/204127739-ca4b810b-7383-4e2f-9d11-ebf708c6571a.png">
> 
> 다크모드에서 공유된 영상은 제대로 글자색상이 지정되지 않습니다. <img alt="image" width="300" src="https://user-images.githubusercontent.com/39216546/204128173-bdb871f0-e6de-4f16-b8d3-2c86cf46efb0.png">
> 
> 온보딩의 색상이 스케치 디자인파일과 다릅니다. <img alt="image" width="300" src="https://user-images.githubusercontent.com/39216546/204129843-576f2feb-92d5-457f-a75a-0e3401208776.png">

1. VideoCollectionView 내에서 편집모드 진입 → 취소 시 네비게이션바 아이템이 제대로 초기화되지 않고 있습니다.
 => 다크모드 작업중 생인 이슈가 아닌 이전 PR에서 생긴 문제 입니다. 
 
 2. 레벨 수정 시 피커의 백그라운드 색상이 어색하게 남아있습니다.
=> 해당뷰는 다른 레벨 선택 화면과 동일한 피커를 넣어서 다시 그려야 합니다. 때문에 다크모드 작업때는 대응하지 않았습니다.

3. 다크모드에서 공유된 영상은 제대로 글자색상이 지정되지 않습니다.
=> 이부분은 확인 해볼게요.

4. 온보딩의 색상이 스케치 디자인파일과 다릅니다.
=> 이것도 확인해 볼게요

2022-11-27 13:47 UTC, RuyHa commented on OrrRock/OrrRock.xcodeproj/project.pbxproj
> -				INFOPLIST_KEY_UIUserInterfaceStyle = Light;
1. 현재 라이트모드 사용자의 경우에는 라이트모드 → 다크모드 → 라이트모드 / 다크모드 사용자의 경우에는 계속 다크모드가 유지되는 형태일텐데, 임의로 컬러모드를 전환시키기 위해서는 viewWillAppear() 호출 시 어떤 함수를 실행 혹은 어떤 설정값을 변경해주면 해주면 되나요?

=> 질문이 이해가 잘 안되는데 앱 실행중에 모드가 변할시 색 변경을 어떻게 하나요? 라고 하신거라면
딱히 뭘 할 필요가 없습니다. 지정된 컬러를 잘 사용 했다면 알아서 변하고, 만약 변하지 않는 값이 있다면
제가 다크모드 대응 이라고 남긴 코멘트를 확인 바랍니다.

2022-11-27 14:09 UTC, sm-amoled commented on OrrRock/OrrRock.xcodeproj/project.pbxproj
> -				INFOPLIST_KEY_UIUserInterfaceStyle = Light;
@RuyHa 질문을 바꿔서, 뷰에 따라 다크모드를 강제할 수는 없나요? 루트파인딩 기능은 모드 구분 없이 동일한 색상을 보여줘야 하는데, 이는 어떻게 처리해야 한다고 생각하시나요?

2022-11-27 14:51 UTC, sm-amoled approved these changes
수정사항 확인했습니다! 수고하셨어요!

2022-11-27 14:56 UTC, merged